// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"NRP_EvalPluginCommand","status":true,"description":"v1.031 プラグインコマンドで数式や制御文字を使用可能に","parameters":{"enableEvaluate":"false","ignoreDoubleBackslash":"true"}},
{"name":"callPluginCommandMZ","status":true,"description":"スクリプトからプラグインコマンドをコール v1.0.0","parameters":{}},
{"name":"SimpleMsgSideViewMZ","status":true,"description":"[Ver1.2.0]サイドビューバトルでスキル/アイテムの名前のみ表示","parameters":{"displayAttack":"true","displayIcon":"false","doesShowDesc":"true","descTiming":"1"}},
{"name":"PluginCommonBase","status":true,"description":"パラメータ解析を提供する共通基盤です","parameters":{}},
{"name":"EventCommandByCode","status":true,"description":"コードとパラメータを指定してイベントコマンドを実行します。","parameters":{}},
{"name":"WindowOff","status":true,"description":"コマンド個別の黒い背景を非表示にします。","parameters":{"windowScrollable":"true","windowHelp":"true","windowMessage":"true","windowMapName":"true","windowBattleLog":"true"}},
{"name":"NRP_WindowBattleLogLayout","status":true,"description":"v1.05 戦闘メッセージのレイアウトを変更します。","parameters":{"<Window Position>":"","x":"this.windowWidth() / 2 - this.width / 2","y":"20","showFront":"false","<Window Size>":"","width":"500","autoWidth":"false","lineHeight":"36","<Window Message>":"","fontSize":"24","padding":"18","<Window Background>":"","normalWindow":"true","backColor":"#000000","backPaintOpacity":"255","gradientType":"0","startGradientSize":"18","endGradientSize":"18"}},
{"name":"NUUN_Base","status":true,"description":"共通処理","parameters":{}},
{"name":"TorigoyaMZ_BattleStatusPosition","status":true,"description":"戦闘画面のステータス表示の位置を人数で調節プラグイン (v.1.0.0)","parameters":{}},
{"name":"NUUN_MaxBattleMembers","status":true,"description":"戦闘メンバー数変更プラグイン","parameters":{"MaxBattleMemberNum":"3"}},
{"name":"NUUN_IconSideBySide","status":true,"description":"戦闘時アクターステート横並び表示","parameters":{"StateIconWidth_X":"0"}},
{"name":"NRP_ChangeParty","status":true,"description":"v1.01 パーティ編成画面を実装。","parameters":{"AllowRelease":"false","ShowOtherPage":"true","ReserveOpacity":"50","StatusType":"level","ChangeDisabledState":"0","<Menu Scene>":"","DisableReserveSkill":"true","DisableReserveFormation":"true","DisableReserveStatus":"false","<Menu Command>":"","ShowMenuCommandPosition":"0","CommandName":"パーティー","MenuCommandSwitch":"","MaskString":"","DisableSwitch":"0"}},
{"name":"MNKR_TimerEX","status":true,"description":"タイマーをカウントアップ・ダウン、表示・非表示を切り替えできるようにします。","parameters":{"countUpSwitch":"10","hideSwitch":"0","countStopValue":"1"}},
{"name":"PANDA_BattleCancelButtonPosition","status":true,"description":"戦闘画面でのキャンセル（戻る）ボタンを非表示または位置を調整します。","parameters":{"DisplayType":"above","Left":"708","Top":"96"}},
{"name":"ShakeOnDamage","status":true,"description":"ダメージ時の振動プラグイン","parameters":{"シェイク強さ":"5","クリティカルシェイク強さ":"9","弱点シェイク強さ":"9","シェイク速さ":"9","シェイク時間":"30","アクターに適用":"true","敵キャラに適用":"false"}},
{"name":"BattleRecord","status":true,"description":"戦績プラグイン","parameters":{}},
{"name":"Timer_Pos","status":true,"description":"","parameters":{"paraX":"0","paraY":"0"}},
{"name":"Jump_Pos","status":true,"description":"","parameters":{}},
{"name":"EnemyAnimation","status":true,"description":"","parameters":{}}
];
